### ISSUE TITLE
SAMLrequest not show

### ISSUE THREAD

**Issue by ggambini** [simplesamlphp/SAML-tracer#71] opened 2021-12-15 10:24 UTC
Hello

Since last update (14 december ?), SAMLtracer on Firefox (78ESR and 95) dont show SAMLrequest, only SAMLresponse.

Regards, Gilian

**Comment by tvdijen** [comment] 2021-12-15 10:54
I can confirm this

**Comment by khlr** [comment] 2021-12-15 11:24
Seems to be related with the updated version of pako:

> Uncaught invalid stored block lengths

I just wonder why this doesn't occour when decoding a SAMLresponse... 🤔

Anyway... I will have a closer look later.
For the meantime I suggest using version 1.6 ... Sorry for this! 😐
https://addons.mozilla.org/firefox/addon/saml-tracer/versions/

**Comment by thijskh** [comment] 2021-12-15 11:49
I have unpublished 1.7 at AMO for now.

**Comment by khlr** [comment] 2022-01-15 01:59
This ist fixed in Version 1.7.1

**Closed by khlr** 2022-01-15 01:59 UTC
